In [3]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
## your code
#np.apply_along_axis(lambda x : pow(2, x) / x, 0, np.arange(1, 21))
f1=lambda x : 2**x / x # or pow(2,x) = 2**x
#lambda function - return 2**x / x
#function pow() - example: pow(x,y) return x**y
np.apply_along_axis(f1, 0, np.arange(1, 21))
#function numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
## your code
#np.sum(np.apply_along_axis(lambda x : pow(0.1, 3*x) * pow(0.2, 4 * x), 0, np.arange(0, 6)), axis = 0)
f2=lambda x : pow(0.1, 3*x) * pow(0.2, 4*x)
s=np.apply_along_axis(f2, 0, np.arange(0, 6))
Sum=np.sum(s, axis = 0)
print(s)
Sum

[1.000000e+00 1.600000e-06 2.560000e-12 4.096000e-18 6.553600e-24
 1.048576e-29]


1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
## your code
#np.apply_along_axis( lambda x : (x + x / 8).astype('int') % 2, 0, np.arange(0, 64)).reshape((8, 8))
f3=lambda x : (x + x / 8).astype('int') % 2
np.apply_along_axis( f3, 0,np.arange(0, 64)).reshape((8, 8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))

## your code
def foo(x, y):
    if (x > 0 and y >= 0):
        return np.arctan(y / x)
    if (x > 0 and y < 0):
        return np.arctan(y / x) + 2 * np.pi
    if (x < 0):
        return np.arctan(y / x) + np.pi
    if (x  == 0 and y > 0):
        return np.pi / 2
    if (x == 0 and y < 0):
        return np.pi * 3 / 2
    if (x == 0 and y == 0):
        return None


f4=lambda x: np.array([np.sqrt(x[0]**2 + x[1] ** 2), foo(x[0], x[1])])
np.apply_along_axis(f4 ,1, X)
#np.apply_along_axis(lambda x: np.array([np.sqrt(x[0]**2 + x[1] ** 2), foo(x[0], x[1])]) ,1, X)

array([[0.04186736, 1.34014919],
       [0.9650203 , 0.40626451],
       [0.50810116, 1.10730935],
       [0.61166902, 1.02918936],
       [0.96995629, 0.30441605]])

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [24]:
X = np.random.random((10, 10))

## your code

res = np.argmax(X)
##Returns the index of the largest number

print( int(res / 10), res % 10 )
##%-Represents modulo, returns the remainder of division

7 8


**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [45]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

##np.argmin(np.apply_along_axis(lambda x : np.sqrt( (x[0] - y[0, 0])** 2 + (x[1] - y[0, 1])**2 ), 1, X))
## your code
f5=lambda x : np.sqrt( (x[0] - y[0, 0])** 2 + (x[1] - y[0, 1])**2 )
NP2=np.apply_along_axis(f5, 1, X)

np.argmin(NP2)

6

**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [26]:
## your code
##definite function
def func(x):
    if (x < 0):
        return x**2 + 2 * x + 6
    elif ( x <= 2):
        return x + 6
    else:
        return x**2 + 4 * x - 4

f  = np.vectorize(func)
##np.vectorize-vectorize the function

In [27]:
f(np.linspace(-3, 3, 100))

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [28]:
X = np.random.random((10, 10))

## your code
X = X - np.apply_along_axis(np.mean, 0, X).T

np.apply_along_axis(np.mean, 0, X).T

#np.mean - average value

array([ 7.77156117e-17,  1.11022302e-17, -3.33066907e-17,  3.33066907e-17,
        1.22124533e-16,  4.44089210e-17, -2.22044605e-17,  1.11022302e-17,
       -4.44089210e-17,  1.11022302e-17])

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [4]:
X = np.random.normal(loc=5, scale=2., size=1000)

## np.mean(X)
## np.mean(np.power(X, 2)) - np.mean(X)**2

sample_mean = np.mean(X)
sample_variance = np.mean(np.power(X, 2)) - pow(np.mean(X),2)

print("Sample mean = ", sample_mean)
print('Sample variance = ',sample_variance )

Sample mean =  5.091338963589722
Sample variance =  3.9672540063514248


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [7]:
## your code
##np.apply_along_axis( lambda x : (x + x / 5).astype('int') % 5, 0, np.arange(0, 25)).reshape((5, 5))
f6=lambda x : (x + x / 5).astype('int') % 5
np.apply_along_axis( f6, 0, np.arange(0, 25)).reshape((5, 5))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [47]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[3, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [31]:
def sample1(x,c):
    assert len(x) > 0
    res = []
    
    s=np.cumsum(x)
    for _ in range(c):
        f=np.where(s>=s[-1]* np.random.random())
        res.append(f[0][0])

    return res

sample1([50, 3, 1, 7, 20],5)   

[4, 0, 0, 4, 1]

In [26]:
r=np.cumsum([50, 3, 1, 7, 20])
s = np.sum([50, 3, 1, 7, 20])
#s*np.random.random()
ee=np.where(r>=r[-1]* np.random.random())
ee[0][0]

4

In [ ]:
##np.cumsum()
##np.where()